[project]
name = "max-pipelines-example"
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
description = "MAX Pipelines"
version = "0.5.0"
authors = ["Modular Inc <hello@modular.com>"]

[dependencies]
max-pipelines = "*"

[tasks]
llama3 = "max llama3"
replit = "max replit"
mistral = "max mistral"
generate = "max generate"
serve = "max serve"
