[project]
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
description = "An example of extending a graph with a custom Mojo operation"
name = "Custom Operations"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
version = "0.1.0"

[tasks]
addition = { cmd = "python addition.py" }
mandelbrot = { cmd = "python mandelbrot.py" }
vector_addition = { cmd = "python vector_addition.py" }
top_k = { cmd = "python top_k.py" }
fused_attention = { cmd = "python fused_attention.py" }
matrix_multiplication = { cmd = "python matrix_multiplication.py" }
histogram = { cmd = "python histogram.py" }
benchmark = { cmd = "mojo benchmarks.mojo" }
whisper = {cmd = "python whisper.py" }
test = { depends-on = [
  "addition",
  "mandelbrot",
  "vector_addition",
  "top_k",
  "fused_attention",
  "matrix_multiplication",
  "benchmark",
  "whisper",
] }

[dependencies]
python = ">=3.9,<3.13"
max = ">=24.6.0.dev2024090821"
