[project]
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/", "pytorch"]
description = "Add a short description here"
name = "max-graph-api"
platforms = ["osx-arm64", "linux-64"]
version = "0.0.0"

[tasks]
add = "mojo add.mojo"
matmul = "mojo matmul.mojo"
mnist = "python mnist.py && mojo mnist.mojo"
test = { depends-on = ["add", "matmul", "mnist"] }

[dependencies]
max = "~=24.6"
pytorch = { version = "==2.6.0", channel = "pytorch" }
torchvision = { version = ">=0.21.0,<0.22", channel = "pytorch" }
numpy = "<2.0"
