[project]
name = "Mojo"
authors = ["Modular <hello@modular.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly/"]
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]

[tasks]
tests = "./stdlib/scripts/run-tests.sh"
format = "mojo format ./stdlib"

[dependencies]
mojo = "<1.0.0"
